# Generated by Django 4.2.8 on 2025-04-03 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_organizer',
            field=models.BooleanField(default=False, help_text='Указывает, имеет ли пользователь права организатора мероприятий', verbose_name='Организатор мероприятий'),
        ),
    ]
